# Generated by Django 3.0.7 on 2020-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20200612_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Image',
            field=models.ImageField(default='', upload_to='Images/'),
        ),
    ]
